### ISSUE TITLE
Utilize GraphQl

### ISSUE THREAD

**Issue by itssoso** [AskYous/sails-my-admin#51]

**Comment by AskYous** [comment]
Any good tutorials/videos you recommend? I have no idea how to use this thing.

**Comment by itssoso** [comment]
looking at this, https://www.howtographql.com/, to understand more of the core concept of what GraphQl is and meant for

**Comment by AskYous** [comment]
I tried sequelize. GraphQL and Sequelize both don't work. Here's a rundown of why we're not using some libraries:

1. **SailsJS** - Not using because the user has to manually define the schema.
2. **Sequelize** - Better than Sails. Automatically makes the schema, but does not define the foreign keys of the schema.
3. **GraphQL** - User still has to manually define the schema.

The main reason we use these tools is to support all databases and they have good tools to write queries without hardcoding them.

---

So the way I see it, we have 2 options:

1. Force the user to manually define the schema in order to use this app. ([I complained to a guy about this but he said others like it.](https://youtu.be/IvsANO0qZEg?t=2520))
2. Just support 1 database for now (like PostgresQL) and write the SQL statements ourselves. This is easier.

What do you think @soullessknight?

**Comment by AskYous** [comment]
The plan:

1. Use plain old SQL statements and support PostgresQL only (for now).
2. Move the PSQL code to its own module.
3. Create other similar modules but for other database technologies.
